### PR TITLE
Adding script from 213362409

### PR DESCRIPTION
**Pull request by lgukhman**

### CODE REVIEW

**Review by sibprogrammer — CHANGES_REQUESTED** [review]
The PHP file should be supplied in non-encrypted form

**Comment by Rosenkreuz1979** [comment]
I guess Leonid should have described that this php file was provided by R&D and was not changed

**Comment by lgukhman** [comment]
I could not find the non-encrypted version anywhere, so providing it as is.

**Comment by sibprogrammer** [comment]
We discussed the situation with Alex K. This file is part of configuration-troubleshooter extension distribution. We should not try to re-distribute its parts separately. Imo, it's better to fix KB article instead.

**Pull request closed without merging**
